# Site settings
author: Jenny Wadkins
title: Jenny's Data Science Blog
header-img: img/home-bg.png
email: threnjen@gmail.com
copyright_name: Jenny Wadkins
description: > # this means to ignore newlines until "baseurl:"
  It's a blog. About data science.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  threnjen

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
